server:
  port : 8098
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      healthcheck:
        enabled : true
      lease:
        duration: 5

spring:
  application:
    name: EmployeeService
management:
  security:
    enabled: false
logging:
  level:
    com.Microservice: DEBUG
